# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
    - linux

julia:
    - 1.0
    - 1.1

script:
    - julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test()'
